enum ArenaSimulatorServer : int {
    Preset,
    Live,
    Dev,
    QA
}
enum Club : int {
    None,
    Engineer,
    CleanNClearing,
    KnightsHospitaller,
    IndeGEHENNA,
    IndeMILLENNIUM,
    IndeHyakkiyako,
    IndeShanhaijing,
    IndeTrinity,
    FoodService,
    Countermeasure,
    BookClub,
    MatsuriOffice,
    GourmetClub,
    HoukagoDessert,
    RedwinterSecretary,
    Schale,
    TheSeminar,
    AriusSqud,
    Justice,
    Fuuki,
    Kohshinjo68,
    Meihuayuan,
    SisterHood,
    GameDev,
    anzenkyoku,
    RemedialClass,
    SPTF,
    TrinityVigilance,
    Veritas,
    TrainingClub,
    Onmyobu,
    Shugyobu,
    Endanbou,
    NinpoKenkyubu,
    Class227,
    EmptyClub,
    Emergentology,
    RabbitPlatoon,
    PandemoniumSociety,
    HotSpringsDepartment,
    TeaParty,
    PublicPeaceBureau,
    Genryumon,
    BlackTortoisePromenade,
    LaborParty,
    KnowledgeLiberationFront,
    Hyakkayouran,
    ShinySparkleSociety,
    AbydosStudentCouncil,
    CentralControlCenter,
    FreightLogisticsDepartment,
    OccultClub,
    PrefectBrigade,
    FreeTradeCartel,
    NicomediasTroop
}
enum ContentType : int {
    None,
    CampaignMainStage,
    CampaignSubStage,
    WeekDungeon,
    EventContentMainStage,
    EventContentSubStage,
    CampaignTutorialStage,
    EventContentMainGroundStage,
    SchoolDungeon,
    TimeAttackDungeon,
    Raid,
    Conquest,
    EventContentStoryStage,
    CampaignExtraStage,
    StoryStrategyStage,
    ScenarioMode,
    EventContent,
    WorldRaid,
    EliminateRaid,
    Chaser,
    FieldContentStage,
    MultiFloorRaid,
    MinigameDefense
}
enum CurrencyTypes : int {
    Invalid,
    Gold,
    GemPaid,
    GemBonus,
    Gem,
    ActionPoint,
    AcademyTicket,
    ArenaTicket,
    RaidTicket,
    WeekDungeonChaserATicket,
    WeekDungeonFindGiftTicket,
    WeekDungeonBloodTicket,
    WeekDungeonChaserBTicket,
    WeekDungeonChaserCTicket,
    SchoolDungeonATicket,
    SchoolDungeonBTicket,
    SchoolDungeonCTicket,
    TimeAttackDungeonTicket,
    MasterCoin,
    WorldRaidTicketA,
    WorldRaidTicketB,
    WorldRaidTicketC,
    ChaserTotalTicket,
    SchoolDungeonTotalTicket,
    EliminateTicketA,
    EliminateTicketB,
    EliminateTicketC,
    EliminateTicketD,
    CafeSummonTicket1,
    CafeSummonTicket2,
    Max
}
enum FieldConditionClass : int {
    AndOr,
    OrAnd,
    Multi
}
enum FieldConditionType : int {
    Invalid,
    Interaction,
    QuestInProgress,
    QuestClear,
    Date,
    StageClear,
    HasKeyword,
    HasEvidence,
    OpenDate,
    OpenDateAfter
}
enum FieldDialogType : int {
    None,
    Talk,
    Think,
    Exclaim,
    Question,
    Upset,
    Surprise,
    Bulb,
    Heart,
    Sweat,
    Angry,
    Music,
    Dot,
    Momotalk,
    Phone,
    Keyword,
    Evidence,
    Chat,
    Keyword_843
}
enum FieldWorldMapButtonType : int {
    DefaultMode,
    Normal,
    Combat,
    Combat_VeryHard,
    UnderCover
}
enum FurnitureLocation : int {
    None,
    Inventory,
    Floor,
    WallLeft,
    WallRight
}
enum MailType : int {
    System,
    Attendance,
    Event,
    MassTrade,
    InventoryFull,
    ArenaDefenseVictory,
    CouponUsageReward,
    ArenaSeasonClose,
    ProductReward,
    MonthlyProductReward,
    ExpiryChangeItem,
    ClanAttendance,
    AccountLink,
    NewUserBonus,
    LeftClanAssistReward,
    AttendanceImmediately,
    WeeklyProductReward,
    BiweeklyProductReward,
    Temp_1,
    Temp_2,
    Temp_3,
    CouponCompleteReward,
    BirthdayMail,
    FromCS,
    ExpiryChangeCurrency,
    ExpiryBattlePassItem,
    FreeProductReward,
    Temp_4,
    Temp_5,
    Temp_6,
    ProductGooglePointReward
}
enum OpenConditionContent : int {
    Shop,
    Gacha,
    LobbyIllust,
    Raid,
    Cafe,
    Unit_Growth_Skill,
    Unit_Growth_LevelUp,
    Unit_Growth_Transcendence,
    Arena,
    Academy,
    Equip,
    Item,
    Favor,
    Prologue,
    Mission,
    WeekDungeon_Chase,
    __Deprecated_WeekDungeon_FindGift,
    __Deprecated_WeekDungeon_Blood,
    Story_Sub,
    Story_Replay,
    WeekDungeon,
    None,
    Shop_Gem,
    Craft,
    Student,
    GuideMission,
    Clan,
    Echelon,
    Campaign,
    EventContent,
    Guild,
    EventStage_1,
    EventStage_2,
    Talk,
    Billing,
    Schedule,
    Story,
    Tactic_Speed,
    Cafe_Invite,
    EventMiniGame_1,
    SchoolDungeon,
    TimeAttackDungeon,
    ShiftingCraft,
    WorldRaid,
    Tactic_Skip,
    Mulligan,
    EventPermanent,
    Main_L_1_2,
    Main_L_1_3,
    Main_L_1_4,
    EliminateRaid,
    Cafe_2,
    Cafe_Invite_2,
    MultiFloorRaid,
    StrategySkip,
    MinigameDreamMaker,
    MiniGameDefense,
    MiniGameCCG
}
enum ParcelType : int {
    None,
    Character,
    Currency,
    Equipment,
    Item,
    GachaGroup,
    Product,
    Shop,
    MemoryLobby,
    AccountExp,
    CharacterExp,
    FavorExp,
    TSS,
    Furniture,
    ShopRefresh,
    LocationExp,
    Recipe,
    CharacterWeapon,
    CharacterGear,
    IdCardBackground,
    Emblem,
    Sticker,
    Costume,
    PossessionCheck,
    BattlePassExp,
    SelectedCharacter,
    UnSelectedCharacter
}
enum Rarity : int {
    N,
    R,
    SR,
    SSR
}
enum RewardTag : int {
    Default,
    FirstClear,
    StrategyObject,
    Event,
    ThreeStar,
    ProductMonthly,
    Rare,
    EventBonus,
    TimeWeight,
    ProductWeekly,
    ProductBiweekly,
    EventPermanentReward,
    ConquestManageEvent,
    ConquestManageDefault,
    ConquestCalculateDefault,
    ConquestCalculateLevel2,
    ConquestCalculateLevel3,
    ConquestFootholdUpgrade2,
    ConquestFootholdUpgrade3,
    ConquestErosionPenalty,
    GemBonus,
    GemPaid,
    ConquestTileConquer
}
enum ScenarioModeReplayTypes : int {
    None,
    Event,
    Favor,
    Work,
    EventMeetup
}
enum ShopCategoryType : int {
    General,
    SecretStone,
    Raid,
    Gold,
    Ap,
    PickupGacha,
    NormalGacha,
    PointGacha,
    EventGacha,
    ArenaTicket,
    Arena,
    TutoGacha,
    RecruitSellection,
    EventContent_0,
    EventContent_1,
    EventContent_2,
    EventContent_3,
    EventContent_4,
    _Obsolete,
    LimitedGacha,
    MasterCoin,
    SecretStoneGrowth,
    TicketGacha,
    DirectPayGacha,
    FesGacha,
    TimeAttack,
    Chaser,
    ChaserTicket,
    SchoolDungeonTicket,
    AcademyTicket,
    Special,
    Care,
    BeforehandGacha,
    EliminateRaid,
    GlobalSpecialGacha,
    SelectPickupGacha,
    GemDaily,
    GemWeekly,
    CafeSummonTicket
}
enum StageDifficulty : int {
    None,
    Normal,
    Hard,
    VeryHard,
    VeryHard_Ex
}
enum StageTopography : int {
    Street,
    Outdoor,
    Indoor
}
enum StrategyEnvironment : int {
    None,
    MapFog
}
enum Tag : int {
    A,
    a,
    B,
    b,
    C,
    c,
    D,
    d,
    E,
    e,
    F,
    f,
    G,
    g,
    H,
    h,
    I,
    i,
    J,
    j,
    K,
    k,
    L,
    l,
    M,
    m,
    N,
    n,
    O,
    o,
    P,
    p,
    Q,
    q,
    R,
    r,
    S,
    s,
    T,
    t,
    U,
    u,
    V,
    v,
    W,
    w,
    X,
    x,
    Y,
    y,
    Z,
    z,
    aA,
    aa,
    aB,
    ab,
    aC,
    ac,
    aD,
    ad,
    aE,
    ae,
    aF,
    af,
    aG,
    ag,
    aH,
    ah,
    aI,
    ai,
    aJ,
    aj,
    aK,
    ak,
    aL,
    al,
    aM,
    am,
    aN,
    an,
    aO,
    ao,
    aP,
    ap,
    aQ,
    aq,
    aR,
    ar,
    aS,
    as,
    aT,
    at,
    aU,
    au,
    aV,
    av,
    aW,
    aw,
    aX,
    ax,
    aY,
    ay,
    aZ,
    az,
    BA,
    Ba,
    BB,
    Bb,
    BC,
    Bc,
    BD,
    Bd,
    BE,
    Be,
    BF,
    Bf,
    BG,
    Bg,
    BH,
    Bh,
    BI,
    Bi,
    BJ,
    Bj,
    BK,
    Bk,
    BL,
    Bl,
    BM,
    Bm,
    BN,
    Bn,
    BO,
    Bo,
    BP,
    Bp,
    BQ,
    Bq,
    BR,
    Br,
    BS,
    Bs,
    BT,
    Bt,
    BU,
    Bu,
    BV,
    Bv,
    BW,
    Bw,
    BX,
    Bx,
    BY,
    By,
    BZ,
    Bz,
    bA,
    ba,
    bB,
    bb,
    bC,
    bc,
    bD,
    bd,
    bE,
    be,
    bF,
    bf,
    bG,
    bg,
    bH,
    bh,
    bI,
    bi,
    bJ,
    bj,
    bK,
    bk,
    bL,
    bl,
    bM,
    bm,
    bN,
    bn,
    bO,
    bo,
    bP,
    bp,
    bQ,
    bq,
    bR,
    br,
    bS,
    bs,
    bT,
    bt,
    bU,
    bu,
    bV,
    bv,
    bW,
    bw,
    bX,
    bx,
    bY,
    by,
    bZ,
    bz,
    CA,
    Ca,
    CB,
    Cb,
    CC,
    Cc,
    CD,
    Cd,
    CE,
    Ce,
    CF,
    Cf,
    CG,
    Cg,
    CH,
    Ch,
    CI,
    Ci,
    CJ,
    Cj,
    CK,
    Ck,
    CL,
    Cl,
    CM,
    Cm,
    CN,
    Cn,
    CO,
    Co,
    CP,
    Cp,
    CQ,
    Cq,
    CR,
    Cr,
    CS,
    Cs,
    CT,
    Ct,
    CU,
    Cu,
    CV,
    Cv,
    CW,
    Cw,
    CX,
    Cx,
    CY,
    Cy,
    CZ,
    Cz,
    cA,
    ca,
    cB,
    cb,
    cC,
    cc,
    cD,
    cd,
    cE,
    ce,
    cF,
    cf,
    cG,
    cg,
    cH,
    ch,
    cI,
    ci,
    cJ,
    cj,
    cK,
    ck,
    cL,
    cl,
    cM,
    cm,
    cN,
    cn,
    cO,
    co,
    cP,
    cp,
    cQ,
    cq,
    cR,
    cr,
    cS,
    cs,
    cT,
    ct,
    cU,
    cu,
    cV,
    cv,
    cW,
    cw,
    cX,
    cx,
    cY,
    cy,
    cZ,
    cz,
    DA,
    Da,
    DB,
    Db,
    DC,
    Dc,
    DD,
    Dd,
    DE,
    De,
    DF,
    Df,
    DG,
    Dg,
    DH,
    Dh,
    DI,
    Di,
    DJ,
    Dj,
    DK,
    Dk,
    DL,
    Dl,
    DM,
    Dm,
    DN,
    Dn,
    DO,
    Do,
    DP,
    Dp,
    DQ,
    Dq,
    DR,
    Dr,
    DS,
    Ds,
    DT,
    Dt,
    DU,
    Du,
    DV,
    Dv,
    DW,
    Dw,
    DX,
    Dx,
    DY,
    Dy,
    DZ,
    Dz,
    dA,
    da,
    dB,
    db,
    dC,
    dc,
    dD,
    dd,
    dE,
    de,
    dF,
    df,
    dG,
    dg,
    dH,
    dh,
    dI,
    di,
    dJ,
    dj,
    dK,
    dk,
    dL,
    dl,
    dM,
    dm,
    dN,
    dn,
    dO,
    do,
    dP,
    dp,
    dQ,
    dq,
    dR,
    dr,
    dS,
    ds,
    dT,
    dt,
    dU,
    du,
    dV,
    dv,
    dW,
    dw,
    dX,
    dx,
    dY,
    dy,
    dZ,
    dz,
    EA,
    Ea,
    EB,
    Eb,
    EC,
    Ec,
    ED,
    Ed,
    EE,
    Ee,
    EF,
    Ef,
    EG,
    Eg,
    EH,
    Eh,
    EI,
    Ei,
    EJ,
    Ej,
    EK,
    Ek,
    EL,
    El,
    EM,
    Em,
    EN,
    En,
    EO,
    Eo,
    EP,
    Ep,
    EQ,
    Eq,
    ER,
    Er,
    ES,
    Es,
    ET,
    Et,
    EU,
    Eu,
    EV,
    Ev,
    EW,
    Ew,
    EX,
    Ex,
    EY,
    Ey,
    EZ,
    Ez,
    eA,
    ea,
    eB,
    eb,
    eC,
    ec,
    eD,
    ed,
    eE,
    ee,
    eF,
    ef,
    eG,
    eg,
    eH,
    eh,
    eI,
    ei,
    eJ,
    ej,
    eK,
    ek,
    eL,
    el,
    eM,
    em,
    eN,
    en,
    eO,
    eo,
    eP,
    ep,
    eQ,
    eq,
    eR,
    er,
    eS,
    es,
    eT,
    et,
    eU,
    eu,
    eV,
    ev,
    eW,
    ew,
    eX,
    ex,
    eY,
    ey,
    eZ,
    ez,
    FA,
    Fa,
    FB,
    Fb,
    FC,
    Fc,
    FD,
    Fd,
    FE,
    Fe,
    FF,
    Ff,
    FG,
    Fg,
    FH,
    Fh,
    FI,
    Fi,
    FJ,
    Fj,
    FK,
    Fk,
    FL,
    Fl,
    FM,
    Fm,
    FN,
    Fn,
    FO,
    Fo,
    FP,
    Fp,
    FQ,
    Fq,
    FR,
    Fr,
    FS,
    Fs,
    FT,
    Ft,
    FU,
    Fu,
    FV,
    Fv,
    FW,
    Fw,
    FX,
    Fx,
    FY,
    Fy,
    FZ,
    Fz,
    fA,
    fa,
    fB,
    fb,
    fC,
    fc,
    fD,
    fd,
    fE,
    fe,
    fF,
    ff,
    fG,
    fg,
    fH,
    fh,
    fI,
    fi,
    fJ,
    fj,
    fK,
    fk,
    fL,
    fl,
    fM,
    fm,
    fN,
    fn,
    fO,
    fo,
    fP,
    fp,
    fQ,
    fq,
    fR,
    fr,
    fS,
    fs,
    fT,
    ft,
    fU,
    fu,
    fV,
    fv,
    fW,
    fw,
    fX,
    fx,
    fY,
    fy,
    fZ,
    fz,
    GA,
    Ga,
    GB,
    Gb,
    GC,
    Gc,
    GD,
    Gd,
    GE,
    Ge,
    GF,
    Gf,
    GG,
    Gg,
    GH,
    Gh,
    GI,
    Gi,
    GJ,
    Gj,
    GK,
    Gk,
    GL,
    Gl,
    GM,
    Gm,
    GN,
    Gn,
    GO,
    Go,
    GP,
    Gp,
    GQ,
    Gq,
    GR,
    Gr,
    GS,
    Gs,
    GT,
    Gt,
    GU,
    Gu,
    GV,
    Gv,
    GW,
    Gw,
    GX,
    Gx,
    GY,
    Gy,
    GZ,
    Gz,
    gA,
    ga,
    gB,
    gb,
    gC,
    gc,
    gD,
    gd,
    gE,
    ge,
    gF,
    gf,
    gG,
    gg,
    gH,
    gh,
    gI,
    gi,
    gJ,
    gj,
    gK,
    gk,
    gL,
    gl,
    gM,
    gm,
    gN,
    gn,
    gO,
    go,
    gP,
    gp,
    gQ,
    gq,
    gR,
    gr,
    gS,
    gs,
    gT,
    gt,
    gU,
    gu,
    gV,
    gv,
    gW,
    gw,
    gX,
    gx,
    gY,
    gy,
    gZ,
    gz,
    HA,
    Ha,
    HB,
    Hb,
    HC,
    Hc,
    HD,
    Hd,
    HE,
    He,
    HF,
    Hf,
    HG,
    Hg,
    HH,
    Hh,
    HI,
    Hi,
    HJ,
    Hj,
    HK,
    Hk,
    HL,
    Hl,
    HM,
    Hm,
    HN,
    Hn,
    HO,
    Ho,
    HP,
    Hp,
    HQ,
    Hq,
    HR,
    Hr,
    HS,
    Hs,
    HT,
    Ht,
    HU,
    Hu,
    HV,
    Hv,
    HW,
    Hw,
    HX,
    Hx,
    HY,
    Hy,
    HZ,
    Hz,
    hA,
    ha,
    hB,
    hb,
    hC,
    hc,
    hD,
    hd,
    hE,
    he,
    hF,
    hf,
    hG,
    hg,
    hH,
    hh,
    hI,
    hi,
    hJ,
    hj,
    hK,
    hk,
    hL,
    hl,
    hM,
    hm,
    hN,
    hn,
    hO,
    ho,
    hP,
    hp,
    hQ,
    hq,
    hR,
    hr,
    hS,
    hs,
    hT,
    ht,
    hU,
    hu,
    hV,
    hv,
    hW,
    hw,
    hX,
    hx,
    hY,
    hy,
    hZ,
    hz,
    IA,
    Ia,
    IB,
    Ib,
    IC,
    Ic,
    ID,
    Id,
    IE,
    Ie,
    IF,
    If,
    IG,
    Ig,
    IH,
    Ih,
    II,
    Ii,
    IJ,
    Ij,
    IK,
    Ik,
    IL,
    Il,
    IM,
    Im,
    IN,
    In,
    IO,
    Io,
    IP,
    Ip,
    IQ,
    Iq,
    IR,
    Ir,
    IS,
    Is,
    IT,
    It,
    IU,
    Iu,
    IV,
    Iv,
    IW,
    Iw,
    IX,
    Ix,
    IY,
    Iy,
    IZ,
    Iz,
    iA,
    ia,
    iB,
    ib,
    iC,
    ic,
    iD,
    id,
    iE,
    ie,
    iF,
    if,
    iG,
    ig,
    iH,
    ih,
    iI,
    ii,
    iJ,
    ij,
    iK,
    ik,
    iL,
    il,
    iM,
    im,
    iN,
    in,
    iO,
    io,
    iP,
    ip,
    iQ,
    iq,
    iR,
    ir,
    iS,
    is,
    iT,
    it,
    iU,
    iu,
    iV,
    iv,
    iW,
    iw,
    iX,
    ix,
    iY,
    iy,
    iZ,
    iz,
    JA,
    Ja,
    JB,
    Jb,
    JC,
    Jc,
    JD,
    Jd,
    JE,
    Je,
    JF,
    Jf,
    JG,
    Jg,
    JH,
    Jh,
    JI,
    Ji,
    JJ,
    Jj,
    JK,
    Jk,
    JL,
    Jl,
    JM,
    Jm,
    JN,
    Jn,
    JO,
    Jo,
    JP,
    Jp,
    JQ,
    Jq,
    JR,
    Jr,
    JS,
    Js,
    JT,
    Jt,
    JU,
    Ju,
    JV,
    Jv,
    JW,
    Jw,
    JX,
    Jx,
    JY,
    Jy,
    JZ,
    Jz,
    jA,
    ja,
    jB,
    jb,
    jC,
    jc,
    jD,
    jd,
    jE,
    je,
    jF,
    jf,
    jG,
    jg,
    jH,
    jh,
    jI,
    ji,
    jJ,
    jj,
    jK,
    jk,
    jL,
    jl,
    jM,
    jm,
    jN,
    jn,
    jO,
    jo,
    jP,
    jp,
    jQ,
    jq,
    jR,
    jr,
    jS,
    js,
    jT,
    jt,
    jU,
    ju,
    jV,
    jv,
    jW,
    jw,
    jX,
    jx,
    jY,
    jy,
    jZ,
    jz,
    KA,
    Ka,
    KB,
    Kb,
    KC,
    Kc,
    KD,
    Kd,
    KE,
    Ke,
    KF,
    Kf,
    KG,
    Kg,
    KH,
    Kh,
    KI,
    Ki,
    KJ,
    Kj,
    KK,
    Kk,
    KL,
    Kl,
    KM,
    Km,
    KN,
    Kn,
    KO,
    Ko,
    KP,
    Kp,
    KQ,
    Kq,
    KR,
    Kr,
    KS,
    Ks,
    KT,
    Kt,
    KU,
    Ku,
    KV,
    Kv,
    KW,
    Kw,
    KX,
    Kx,
    KY,
    Ky,
    KZ,
    Kz,
    kA,
    ka,
    kB,
    kb,
    kC,
    kc,
    kD,
    kd,
    kE,
    ke,
    kF,
    kf,
    kG,
    kg,
    kH,
    kh,
    kI,
    ki,
    kJ,
    kj,
    kK,
    kk,
    kL,
    kl,
    kM,
    km,
    kN,
    kn,
    kO,
    ko,
    kP,
    kp,
    kQ,
    kq,
    kR,
    kr,
    kS,
    ks,
    kT,
    kt,
    kU,
    ku,
    kV,
    kv,
    kW,
    kw,
    kX,
    kx,
    kY,
    ky,
    kZ,
    kz,
    LA,
    La,
    LB,
    Lb,
    LC,
    Lc,
    LD,
    Ld,
    LE,
    Le,
    LF,
    Lf,
    LG,
    Lg,
    LH,
    Lh,
    LI,
    Li,
    LJ,
    Lj,
    LK,
    Lk,
    LL,
    Ll,
    LM,
    Lm,
    LN,
    Ln,
    LO,
    Lo,
    LP,
    Lp,
    LQ,
    Lq,
    LR,
    Lr,
    LS,
    Ls,
    LT,
    Lt,
    LU,
    Lu,
    LV,
    Lv,
    LW,
    Lw,
    LX,
    Lx,
    LY,
    Ly,
    LZ,
    Lz,
    lA,
    la,
    lB,
    lb,
    lC,
    lc,
    lD,
    ld,
    lE,
    le,
    lF,
    lf,
    lG,
    lg,
    lH,
    lh,
    lI,
    li,
    lJ,
    lj,
    lK,
    lk,
    lL,
    ll,
    lM,
    lm,
    lN,
    ln,
    lO,
    lo,
    lP,
    lp,
    lQ,
    lq,
    lR,
    lr,
    lS,
    ls,
    lT,
    lt,
    lU,
    lu,
    lV,
    lv,
    lW,
    lw,
    lX,
    lx,
    lY,
    ly,
    lZ,
    lz,
    MA,
    Ma,
    MB,
    Mb,
    MC,
    Mc,
    MD,
    Md,
    ME,
    Me,
    MF,
    Mf,
    MG,
    Mg,
    MH,
    Mh,
    MI,
    Mi,
    MJ,
    Mj,
    MK,
    Mk,
    ML,
    Ml,
    MM,
    Mm,
    MN,
    Mn,
    MO,
    Mo,
    MP,
    Mp,
    MQ,
    Mq,
    MR,
    Mr,
    MS,
    Ms,
    MT,
    Mt,
    MU,
    Mu,
    MV,
    Mv,
    MW,
    Mw,
    MX,
    Mx,
    MY,
    My,
    MZ,
    Mz,
    mA,
    ma,
    mB,
    mb,
    mC,
    mc,
    mD,
    md,
    mE,
    me,
    mF,
    mf,
    mG,
    mg,
    mH,
    mh,
    mI,
    mi,
    mJ,
    mj,
    mK,
    mk,
    mL,
    ml,
    mM,
    mm,
    mN,
    mn,
    mO,
    mo,
    mP,
    mp,
    mQ,
    mq,
    mR,
    mr,
    mS,
    ms,
    mT,
    mt,
    mU,
    mu,
    mV,
    mv,
    mW,
    mw,
    mX,
    mx,
    mY,
    my,
    mZ,
    mz,
    NA,
    Na,
    NB,
    Nb,
    NC,
    Nc,
    ND,
    Nd,
    NE,
    Ne,
    NF,
    Nf,
    NG,
    Ng,
    NH,
    Nh,
    NI,
    Ni,
    NJ,
    Nj,
    NK,
    Nk,
    NL,
    Nl,
    NM,
    Nm,
    NN,
    Nn,
    NO,
    No,
    NP,
    Np,
    NQ,
    Nq,
    NR,
    Nr,
    NS,
    Ns,
    NT,
    Nt,
    NU,
    Nu,
    NV,
    Nv,
    NW,
    Nw,
    NX,
    Nx,
    NY,
    Ny,
    NZ,
    Nz,
    nA,
    na,
    nB,
    nb,
    nC,
    nc,
    nD,
    nd,
    nE,
    ne,
    nF,
    nf,
    nG,
    ng,
    nH,
    nh,
    nI,
    ni,
    nJ,
    nj,
    nK,
    nk,
    nL,
    nl,
    nM,
    nm,
    nN,
    nn,
    nO,
    no,
    nP,
    np,
    nQ,
    nq,
    nR,
    nr,
    nS,
    ns,
    nT,
    nt,
    nU,
    nu,
    nV,
    nv,
    nW,
    nw,
    nX,
    nx,
    nY,
    ny,
    nZ,
    nz,
    OA,
    Oa,
    OB,
    Ob,
    OC,
    Oc,
    OD,
    Od,
    OE,
    Oe,
    OF,
    Of,
    OG,
    Og,
    OH,
    Oh,
    OI,
    Oi,
    OJ,
    Oj,
    OK,
    Ok,
    OL,
    Ol,
    OM,
    Om,
    ON,
    On,
    OO,
    Oo,
    OP,
    Op,
    OQ,
    Oq,
    OR,
    Or,
    OS,
    Os,
    OT,
    Ot,
    OU,
    Ou,
    OV,
    Ov,
    OW,
    Ow,
    OX,
    Ox,
    OY,
    Oy,
    OZ,
    Oz,
    oA,
    oa,
    oB,
    ob,
    oC,
    oc,
    oD,
    od,
    oE,
    oe,
    oF,
    of,
    oG,
    og,
    oH,
    oh,
    oI,
    oi,
    oJ,
    oj,
    oK,
    ok,
    oL,
    ol,
    oM,
    om,
    oN,
    on,
    oO,
    oo,
    oP,
    op,
    oQ,
    oq,
    oR,
    or,
    oS,
    os,
    oT,
    ot,
    oU,
    ou,
    oV,
    ov,
    oW,
    ow,
    oX,
    ox,
    oY,
    oy,
    oZ,
    oz,
    PA,
    Pa,
    PB,
    Pb,
    PC,
    Pc,
    PD,
    Pd,
    PE,
    Pe,
    PF,
    Pf,
    PG,
    Pg,
    PH,
    Ph,
    PI,
    Pi,
    PJ,
    Pj,
    PK,
    Pk,
    PL,
    Pl,
    PM,
    Pm,
    PN,
    Pn,
    PO,
    Po,
    PP,
    Pp,
    PQ,
    Pq,
    PR,
    Pr,
    PS,
    Ps,
    PT,
    Pt,
    PU,
    Pu,
    PV,
    Pv,
    PW,
    Pw,
    PX,
    Px,
    PY,
    Py,
    PZ,
    Pz,
    pA,
    pa,
    pB,
    pb,
    pC,
    pc,
    pD,
    pd,
    pE,
    pe,
    pF,
    pf,
    pG,
    pg,
    pH,
    ph,
    pI,
    pi,
    pJ,
    pj,
    pK,
    pk,
    pL,
    pl,
    pM,
    pm,
    pN,
    pn,
    pO,
    po,
    pP,
    pp,
    pQ,
    pq,
    pR,
    pr,
    pS,
    ps,
    pT,
    pt,
    pU,
    pu,
    pV,
    pv,
    pW,
    pw,
    pX,
    px,
    pY,
    py,
    pZ,
    pz,
    QA,
    Qa,
    QB,
    Qb,
    QC,
    Qc,
    QD,
    Qd,
    QE,
    Qe,
    QF,
    Qf,
    QG,
    Qg,
    QH,
    Qh,
    QI,
    Qi,
    QJ,
    Qj,
    QK,
    Qk,
    QL,
    Ql,
    QM,
    Qm,
    QN,
    Qn,
    QO,
    Qo,
    QP,
    Qp,
    QQ,
    Qq,
    QR,
    Qr,
    QS,
    Qs,
    QT,
    Qt,
    QU,
    Qu,
    QV,
    Qv,
    QW,
    Qw,
    QX,
    Qx,
    QY,
    Qy,
    QZ,
    Qz,
    qA,
    qa,
    qB,
    qb,
    qC,
    qc,
    qD,
    qd,
    qE,
    qe,
    qF,
    qf,
    qG,
    qg,
    qH,
    qh,
    qI,
    qi,
    qJ,
    qj,
    qK,
    qk,
    qL,
    ql,
    qM,
    qm,
    qN,
    qn,
    qO,
    qo,
    qP,
    qp,
    qQ,
    qq,
    qR,
    qr,
    qS,
    qs,
    qT,
    qt,
    qU,
    qu,
    qV,
    qv,
    qW,
    qw,
    qX,
    qx,
    qY,
    qy,
    qZ,
    qz,
    RA,
    Ra,
    RB,
    Rb,
    RC,
    Rc,
    RD,
    Rd,
    RE,
    Re,
    RF,
    Rf,
    RG,
    Rg,
    RH,
    Rh,
    RI,
    Ri,
    RJ,
    Rj,
    RK,
    Rk,
    RL,
    Rl,
    RM,
    Rm,
    RN,
    Rn,
    RO,
    Ro,
    RP,
    Rp,
    RQ,
    Rq,
    RR,
    Rr,
    RS,
    Rs,
    RT,
    Rt,
    RU,
    Ru,
    RV,
    Rv,
    RW,
    Rw,
    RX,
    Rx,
    RY,
    Ry,
    RZ,
    Rz,
    rA,
    ra,
    rB,
    rb,
    rC,
    rc,
    rD,
    rd,
    rE,
    re,
    rF,
    rf,
    rG,
    rg,
    rH,
    rh,
    rI,
    ri,
    rJ,
    rj,
    rK,
    rk,
    rL,
    rl,
    rM,
    rm,
    rN,
    rn,
    rO,
    ro,
    rP,
    rp,
    rQ,
    rq,
    rR,
    rr,
    rS,
    rs,
    rT,
    rt,
    rU,
    ru,
    rV,
    rv,
    rW,
    rw,
    rX,
    rx,
    rY,
    ry,
    rZ,
    rz,
    SA,
    Sa,
    SB,
    Sb,
    SC,
    Sc,
    SD,
    Sd,
    SE,
    Se,
    SF,
    Sf,
    SG,
    Sg,
    SH,
    Sh,
    SI,
    Si,
    SJ,
    Sj,
    SK,
    Sk,
    SL,
    Sl,
    SM,
    Sm,
    SN,
    Sn,
    SO,
    So,
    SP,
    Sp,
    SQ,
    Sq,
    SR,
    Sr,
    SS,
    Ss,
    ST,
    St,
    SU,
    Su,
    SV,
    Sv,
    SW,
    Sw,
    SX,
    Sx,
    SY,
    Sy,
    SZ,
    Sz,
    sA,
    sa,
    sB,
    sb,
    sC,
    sc,
    sD,
    sd,
    sE,
    se,
    sF,
    sf,
    sG,
    sg,
    sH,
    sh,
    sI,
    si,
    sJ,
    sj,
    sK,
    sk,
    sL,
    sl,
    sM,
    sm,
    sN,
    sn,
    sO,
    so,
    sP,
    sp,
    sQ,
    sq,
    sR,
    sr,
    sS,
    ss,
    sT,
    st,
    sU,
    su,
    sV,
    sv,
    sW,
    sw,
    sX,
    sx,
    sY,
    sy,
    sZ,
    sz,
    TA,
    Ta,
    TB,
    Tb,
    TC,
    Tc,
    TD,
    Td,
    TE,
    Te,
    TF,
    Tf,
    TG,
    Tg,
    TH,
    Th,
    TI,
    Ti,
    TJ,
    Tj,
    TK,
    Tk,
    TL,
    Tl,
    TM,
    Tm,
    TN,
    Tn,
    TO,
    To,
    TP,
    Tp,
    TQ,
    Tq,
    TR,
    Tr,
    TS,
    Ts,
    TT,
    Tt,
    TU,
    Tu,
    TV,
    Tv,
    TW,
    Tw,
    TX,
    Tx,
    TY,
    Ty,
    TZ,
    Tz,
    tA,
    ta,
    tB,
    tb,
    tC,
    tc,
    tD,
    td,
    tE,
    te,
    tF,
    tf,
    tG,
    tg,
    tH,
    th,
    tI,
    ti,
    tJ,
    tj,
    tK,
    tk,
    tL,
    tl,
    tM,
    tm,
    tN,
    tn,
    tO,
    to,
    tP,
    tp,
    tQ,
    tq,
    tR,
    tr,
    tS,
    ts,
    tT,
    tt,
    tU,
    tu,
    tV,
    tv,
    tW,
    tw,
    tX,
    tx,
    tY,
    ty,
    tZ,
    tz,
    UA,
    Ua,
    UB,
    Ub,
    UC,
    Uc,
    UD,
    Ud,
    UE,
    Ue,
    UF,
    Uf,
    UG,
    Ug,
    UH,
    Uh,
    UI,
    Ui,
    UJ,
    Uj,
    UK,
    Uk,
    UL,
    Ul,
    UM,
    Um,
    UN,
    Un,
    UO,
    Uo,
    UP,
    Up,
    UQ,
    Uq,
    UR,
    Ur,
    US,
    Us,
    UT,
    Ut,
    UU,
    Uu,
    UV,
    Uv,
    UW,
    Uw,
    UX,
    Ux,
    UY,
    Uy,
    UZ,
    Uz,
    uA,
    ua,
    uB,
    ub,
    uC,
    uc,
    uD,
    ud,
    uE,
    ue,
    uF,
    uf,
    uG,
    ug,
    uH,
    uh,
    uI,
    ui,
    uJ,
    uj,
    uK,
    uk,
    uL,
    ul,
    uM,
    um,
    uN,
    un,
    uO,
    uo,
    uP,
    up,
    uQ,
    uq,
    uR,
    ur,
    uS,
    us,
    uT,
    ut,
    uU,
    uu,
    uV,
    uv,
    uW,
    uw,
    uX,
    ux,
    uY,
    uy,
    uZ,
    uz,
    VA,
    Va,
    VB,
    Vb,
    VC,
    Vc,
    VD,
    Vd,
    VE,
    Ve,
    VF,
    Vf,
    VG,
    Vg,
    VH,
    Vh,
    VI,
    Vi,
    VJ,
    Vj,
    VK,
    Vk,
    VL,
    Vl,
    VM,
    Vm,
    VN,
    Vn,
    VO,
    Vo,
    VP,
    Vp,
    VQ,
    Vq,
    VR,
    Vr,
    VS,
    Vs,
    VT,
    Vt,
    VU,
    Vu,
    VV,
    Vv,
    VW,
    Vw,
    VX,
    Vx,
    VY,
    Vy,
    VZ,
    Vz,
    vA,
    va,
    vB,
    vb,
    vC,
    vc,
    vD,
    vd,
    vE,
    ve,
    vF,
    vf,
    vG,
    vg,
    vH,
    vh,
    vI,
    vi,
    vJ,
    vj,
    vK,
    vk,
    vL,
    vl,
    vM,
    vm,
    vN,
    vn,
    vO,
    vo,
    vP,
    vp,
    vQ,
    vq,
    vR,
    vr,
    vS,
    vs,
    vT,
    vt,
    vU,
    vu,
    vV,
    vv,
    vW,
    vw,
    vX,
    vx,
    vY,
    vy,
    vZ,
    vz,
    WA,
    Wa,
    WB,
    Wb,
    WC,
    Wc,
    WD,
    Wd,
    WE,
    We,
    WF,
    Wf,
    WG,
    Wg,
    WH,
    Wh,
    WI,
    Wi,
    WJ,
    Wj,
    WK,
    Wk,
    WL,
    Wl,
    WM,
    Wm,
    WN,
    Wn,
    WO,
    Wo,
    WP,
    Wp,
    WQ,
    Wq,
    WR,
    Wr,
    WS,
    Ws,
    WT,
    Wt,
    WU,
    Wu,
    WV,
    Wv,
    WW,
    Ww,
    WX,
    Wx,
    WY,
    Wy,
    WZ,
    Wz,
    wA,
    wa,
    wB,
    wb,
    wC,
    wc,
    wD,
    wd,
    wE,
    we,
    wF,
    wf,
    wG,
    wg,
    wH,
    wh,
    wI,
    wi,
    wJ,
    wj,
    wK,
    wk,
    wL,
    wl,
    wM,
    wm,
    wN,
    wn,
    wO,
    wo,
    wP,
    wp,
    wQ,
    wq,
    wR,
    wr,
    wS,
    ws,
    wT,
    wt,
    wU,
    wu,
    wV,
    wv,
    wW,
    ww,
    wX,
    wx,
    wY,
    wy,
    wZ,
    wz,
    XA,
    Xa,
    XB,
    Xb,
    XC,
    Xc,
    XD,
    Xd,
    XE,
    Xe,
    XF,
    Xf,
    XG,
    Xg,
    XH,
    Xh,
    XI,
    Xi,
    XJ,
    Xj,
    XK,
    Xk,
    XL,
    Xl,
    XM,
    Xm,
    XN,
    Xn,
    XO,
    Xo,
    XP,
    Xp,
    XQ,
    Xq,
    XR,
    Xr,
    XS,
    Xs,
    XT,
    Xt,
    XU,
    Xu,
    XV,
    Xv,
    XW,
    Xw,
    XX,
    Xx,
    XY,
    Xy,
    XZ,
    Xz,
    xA,
    xa,
    xB,
    xb,
    xC,
    xc,
    xD,
    xd,
    xE,
    xe,
    xF,
    xf,
    xG,
    xg,
    xH,
    xh,
    xI,
    xi,
    xJ,
    xj,
    xK,
    xk,
    xL,
    xl,
    xM,
    xm,
    xN,
    xn,
    xO,
    xo,
    xP,
    xp,
    xQ,
    xq,
    xR,
    xr,
    xS,
    xs,
    xT,
    xt,
    xU,
    xu,
    xV,
    xv,
    xW,
    xw,
    xX,
    xx,
    xY,
    xy,
    xZ,
    xz,
    YA,
    Ya,
    YB,
    Yb,
    YC,
    Yc,
    YD,
    Yd,
    YE,
    Ye,
    YF,
    Yf,
    YG,
    Yg,
    YH,
    Yh,
    YI,
    Yi,
    YJ,
    Yj,
    YK,
    Yk,
    YL,
    Yl,
    YM,
    Ym,
    YN,
    Yn,
    YO,
    Yo,
    YP,
    Yp,
    YQ,
    Yq,
    YR,
    Yr,
    YS,
    Ys,
    YT,
    Yt,
    YU,
    Yu,
    YV,
    Yv,
    YW,
    Yw,
    YX,
    Yx,
    YY,
    Yy,
    YZ,
    Yz,
    yA,
    ya,
    yB,
    yb,
    yC,
    yc,
    yD,
    yd,
    yE,
    ye,
    yF,
    yf,
    yG,
    yg,
    yH,
    yh,
    yI,
    yi,
    yJ,
    yj,
    yK,
    yk,
    yL,
    yl,
    yM,
    ym,
    yN,
    yn,
    yO,
    yo,
    yP,
    yp,
    yQ,
    yq,
    yR,
    yr,
    yS,
    ys,
    yT,
    yt,
    yU,
    yu,
    yV,
    yv,
    yW,
    yw,
    yX,
    yx,
    yY,
    yy,
    yZ,
    yz,
    ZA,
    Za,
    ZB,
    Zb,
    ZC,
    Zc,
    ZD,
    Zd,
    ZE,
    Ze,
    ZF,
    Zf,
    ZG,
    Zg,
    ZH,
    Zh,
    ZI,
    Zi,
    ZJ,
    Zj,
    ZK,
    Zk,
    ZL,
    Zl,
    ZM,
    Zm,
    ZN,
    Zn,
    ZO,
    Zo,
    ZP,
    Zp,
    ZQ,
    Zq,
    ZR,
    Zr,
    ZS,
    Zs,
    ZT,
    Zt,
    ZU,
    Zu,
    ZV,
    Zv,
    ZW,
    Zw,
    ZX,
    Zx,
    ZY,
    Zy,
    ZZ,
    Zz,
    zA,
    za,
    zB,
    zb,
    zC,
    zc,
    zD,
    zd,
    zE,
    ze,
    zF,
    zf,
    zG,
    zg,
    zH,
    zh,
    zI,
    zi,
    zJ,
    zj,
    zK,
    zk,
    zL,
    zl,
    zM,
    zm,
    zN,
    zn,
    zO,
    zo,
    zP,
    zp,
    zQ,
    zq,
    zR,
    zr,
    zS,
    zs,
    zT,
    zt,
    zU,
    zu,
    zV,
    zv,
    zW,
    zw,
    zX,
    zx,
    zY,
    zy,
    zZ,
    zz,
    aAA,
    aAa,
    aAB,
    aAb,
    aAC,
    aAc,
    aAD,
    aAd,
    aAE,
    aAe,
    aAF,
    aAf,
    aAG,
    aAg,
    aAH,
    aAh,
    aAI,
    aAi,
    aAJ,
    aAj,
    aAK,
    aAk,
    aAL,
    aAl,
    aAM,
    aAm,
    aAN,
    aAn,
    aAO,
    aAo,
    aAP,
    aAp,
    aAQ,
    aAq,
    aAR,
    aAr,
    aAS,
    aAs,
    aAT,
    aAt,
    aAU,
    aAu,
    aAV,
    aAv,
    aAW,
    aAw,
    aAX,
    aAx,
    aAY,
    aAy,
    aAZ,
    aAz,
    aaA,
    aaa,
    aaB,
    aab,
    aaC,
    aac,
    aaD,
    aad,
    aaE,
    aae,
    aaF,
    aaf,
    aaG,
    aag,
    aaH,
    aah,
    aaI,
    aai,
    aaJ,
    aaj,
    aaK,
    aak,
    aaL,
    aal,
    aaM,
    aam,
    aaN,
    aan,
    aaO,
    aao,
    aaP,
    aap,
    aaQ,
    aaq,
    aaR,
    aar,
    aaS,
    aas,
    aaT,
    aat,
    aaU,
    aau,
    aaV,
    aav,
    aaW,
    aaw,
    aaX,
    aax,
    aaY,
    aay,
    aaZ,
    aaz,
    aBA,
    aBa,
    aBB,
    aBb,
    aBC,
    aBc,
    aBD,
    aBd,
    aBE,
    aBe,
    aBF,
    aBf,
    aBG,
    aBg,
    aBH,
    aBh,
    aBI,
    aBi,
    aBJ,
    aBj,
    aBK,
    aBk,
    aBL,
    aBl,
    aBM,
    aBm,
    aBN,
    aBn,
    aBO,
    aBo,
    aBP,
    aBp,
    aBQ,
    aBq,
    aBR,
    aBr,
    aBS,
    aBs,
    aBT,
    aBt,
    aBU,
    aBu,
    aBV,
    aBv,
    aBW,
    aBw,
    aBX,
    aBx,
    aBY,
    aBy,
    aBZ,
    aBz,
    abA,
    aba,
    abB,
    abb,
    abC,
    abc,
    abD,
    abd,
    abE,
    abe,
    abF,
    abf,
    abG,
    abg,
    abH,
    abh,
    abI,
    abi,
    abJ,
    abj,
    abK,
    abk,
    abL,
    abl,
    abM,
    abm,
    abN,
    abn,
    abO,
    abo,
    abP,
    abp,
    abQ,
    abq,
    abR,
    abr,
    abS,
    abs,
    abT,
    abt,
    abU,
    abu,
    abV,
    abv,
    abW,
    abw,
    abX,
    abx,
    abY,
    aby,
    abZ,
    abz,
    aCA,
    aCa,
    aCB,
    aCb,
    aCC,
    aCc,
    aCD,
    aCd,
    aCE,
    aCe,
    aCF,
    aCf,
    aCG,
    aCg,
    aCH,
    aCh,
    aCI,
    aCi,
    aCJ,
    aCj,
    aCK,
    aCk,
    aCL,
    aCl,
    aCM,
    aCm,
    aCN,
    aCn,
    aCO,
    aCo,
    aCP,
    aCp,
    aCQ,
    aCq,
    aCR,
    aCr,
    aCS,
    aCs,
    aCT,
    aCt,
    aCU,
    aCu,
    aCV,
    aCv,
    aCW,
    aCw,
    aCX,
    aCx,
    aCY,
    aCy,
    aCZ,
    aCz,
    acA,
    aca,
    acB,
    acb,
    acC,
    acc,
    acD,
    acd,
    acE,
    ace,
    acF,
    acf,
    acG,
    acg,
    acH,
    ach,
    acI,
    aci,
    acJ,
    acj,
    acK,
    ack,
    acL,
    acl,
    acM,
    acm,
    acN,
    acn,
    acO,
    aco,
    acP,
    acp,
    acQ,
    acq,
    acR,
    acr,
    acS,
    acs,
    acT,
    act
}
enum TerrainAdaptationStat : int {
    D,
    C,
    B,
    A,
    S,
    SS
}
table AniEventData {
    Name: string;
    Time: float;
    IntParam: int;
    FloatParam: float;
    StringParam: string;
}
table BlendInfo {
    From: int;
    To: int;
    Blend: float;
}
table BossPhaseExcel {
    Id: long;
    AIPhase: long;
    NormalAttackSkillUniqueName: string;
    UseExSkill: [bool];
}
table CharacterDialogEmojiExcel {
    GroupId: long;
    TargetIndex: int;
    DialogType: string;
    Duration: long;
    HideUI: bool;
    LocalizeKR: string;
    LocalizeJP: string;
}
table ConstAudioExcel {
    DefaultSnapShotName: string;
    BattleSnapShotName: string;
    RaidSnapShotName: string;
    ExSkillCutInSnapShotName: string;
}
table ConstCombatExcel {
    SkillHandCount: int;
    DyingTime: int;
    BuffIconBlinkTime: int;
    ShowBufficonEXSkill: bool;
    ShowBufficonPassiveSkill: bool;
    ShowBufficonExtraPassiveSkill: bool;
    ShowBufficonLeaderSkill: bool;
    ShowBufficonGroundPassiveSkill: bool;
    SuppliesConditionStringId: string;
    PublicSpeechBubbleOffsetX: float;
    PublicSpeechBubbleOffsetY: float;
    PublicSpeechBubbleOffsetZ: float;
    ShowRaidListCount: int;
    MaxRaidTicketCount: long;
    MaxRaidBossSkillSlot: long;
    EngageTimelinePath: string;
    EngageWithSupporterTimelinePath: string;
    VictoryTimelinePath: string;
    TimeLimitAlarm: long;
    EchelonMaxCommonCost: int;
    EchelonInitCommonCost: int;
    SkillSlotCoolTime: long;
    EnemyRegenCost: long;
    ChampionRegenCost: long;
    PlayerRegenCostDelay: long;
    CrowdControlFactor: long;
    RaidOpenScenarioId: string;
    EliminateRaidOpenScenarioId: string;
    DefenceConstA: long;
    DefenceConstB: long;
    DefenceConstC: long;
    DefenceConstD: long;
    AccuracyConstA: long;
    AccuracyConstB: long;
    AccuracyConstC: long;
    AccuracyConstD: long;
    CriticalConstA: long;
    CriticalConstB: long;
    CriticalConstC: long;
    CriticalConstD: long;
    MaxGroupBuffLevel: int;
    EmojiDefaultTime: int;
    TimeLineActionRotateSpeed: long;
    BodyRotateSpeed: long;
    NormalTimeScale: long;
    FastTimeScale: long;
    BulletTimeScale: long;
    UIDisplayDelayAfterSkillCutIn: long;
    UseInitialRangeForCoverMove: bool;
    SlowTimeScale: long;
    AimIKMinDegree: float;
    AimIKMaxDegree: float;
    MinimumClearTime: int;
    MinimumClearLevelGap: int;
    CheckCheaterMaxUseCostNonArena: int;
    CheckCheaterMaxUseCostArena: int;
    AllowedMaxTimeScale: long;
    RandomAnimationOutput: long;
    SummonedTeleportDistance: long;
    ArenaMinimumClearTime: int;
    WORLDBOSSBATTLELITTLE: long;
    WORLDBOSSBATTLEMIDDLE: long;
    WORLDBOSSBATTLEHIGH: long;
    WORLDBOSSBATTLEVERYHIGH: long;
    WorldRaidAutoSyncTermSecond: long;
    WorldRaidBossHpDecreaseTerm: long;
    WorldRaidBossParcelReactionDelay: long;
    RaidRankingJumpMinimumWaitingTime: long;
    EffectTeleportDistance: float;
    AuraExitThresholdMargin: long;
    TSAInteractionDamageFactor: long;
    VictoryInteractionRate: long;
    EchelonExtensionEngageTimelinePath: string;
    EchelonExtensionEngageWithSupporterTimelinePath: string;
    EchelonExtensionVictoryTimelinePath: string;
    EchelonExtensionEchelonMaxCommonCost: int;
    EchelonMaxOverloadCost: long;
    EchelonExtensionMaxOverloadCost: long;
    EchelonExtensionEchelonInitCommonCost: int;
    EchelonExtensionCostRegenRatio: long;
    EchelonOverloadCostRegenRatio: long;
    EchelonExtensionOverloadCostRegenRatio: long;
    CheckCheaterMaxUseCostMultiFloorRaid: int;
    ExcessiveTouchCheckTime: float;
    ExcessiveTouchCheckCount: int;
    CampaignAlertPopupLevelGap: int;
    MoveCorrectionSkipRatio: int;
}
table ConstConquestExcel {
    ManageUnitChange: int;
    AssistCount: int;
    PlayTimeLimitInSeconds: int;
    AnimationUnitAmountMin: int;
    AnimationUnitAmountMax: int;
    AnimationUnitDelay: float;
}
table ConstFieldExcel {
    DialogSmoothTime: int;
    TalkDialogDurationDefault: int;
    ThinkDialogDurationDefault: int;
    IdleThinkDelayMin: int;
    IdleThinkDelayMax: int;
}
table ConstMinigameCCGExcel {
    TurnDrawCount: int;
    ConquestMapBoundaryOffsetRight: float;
    ConquestMapBoundaryOffsetTop: float;
    ConquestMapBoundaryOffsetBottom: float;
    ConquestMapCenterOffsetX: float;
    ConquestMapCenterOffsetY: float;
    CameraAngle: float;
    CameraZoomMax: float;
    CameraZoomMin: float;
    CameraZoomDefault: float;
    ThemaLoadingProgressTime: float;
    MapAllyRotation: float;
    AniAllyBattleAttack: string;
    MaxHandCount: int;
    MaxCost: int;
    StartCost: int;
    TurnCost: int;
    StrikerSwapFrontCost: int;
    StrikerMaxEquipCount: int;
    StartDrawCount: int;
    CampReviveHealthRate: int;
    BaseRewardRerollPoint: int;
    SelectRewardOptionCount: int;
    AlternativeCardImagePath: string;
}
table ConstMinigameRoadPuzzleExcel {
    RoadPuzzleMapBoundaryOffsetLeft: float;
    RoadPuzzleMapBoundaryOffsetRight: float;
    RoadPuzzleMapBoundaryOffsetTop: float;
    RoadPuzzleMapBoundaryOffsetBottom: float;
    RoadPuzzleMapCenterOffsetX: float;
    RoadPuzzleMapCenterOffsetY: float;
    CameraAngle: float;
    CameraZoomMax: float;
    CameraZoomMin: float;
    CameraZoomDefault: float;
    StageLoadingProgressTime: float;
    TileRotationDegree: int;
    StartStageIndex: int;
    LoopStageIndex: int;
}
table ConstMiniGameShootingExcel {
    NormalStageId: long;
    NormalSectionCount: int;
    HardStageId: long;
    HardSectionCount: int;
    FreeStageId: long;
    FreeSectionCount: int;
    PlayerCharacterId: [long];
    HiddenPlayerCharacterId: long;
    CameraSmoothTime: float;
    SpawnEffectPath: string;
    WaitTimeAfterSpawn: float;
    FreeGearInterval: int;
}
table ConstMinigameTBGExcel {
    ConquestMapBoundaryOffsetLeft: float;
    ConquestMapBoundaryOffsetRight: float;
    ConquestMapBoundaryOffsetTop: float;
    ConquestMapBoundaryOffsetBottom: float;
    ConquestMapCenterOffsetX: float;
    ConquestMapCenterOffsetY: float;
    CameraAngle: float;
    CameraZoomMax: float;
    CameraZoomMin: float;
    CameraZoomDefault: float;
    ThemaLoadingProgressTime: float;
    MapAllyRotation: float;
    AniAllyBattleAttack: string;
    EffectAllyBattleAttack: string;
    EffectAllyBattleDamage: string;
    AniEnemyBattleAttack: string;
    EffectEnemyBattleAttack: string;
    EffectEnemyBattleDamage: string;
    EncounterAllyRotation: float;
    EncounterEnemyRotation: float;
    EncounterRewardReceiveIndex: int;
}
table ConstNewbieContentExcel {
    NewbieGachaReleaseDate: string;
    NewbieGachaCheckDays: int;
    NewbieGachaTokenGraceTime: int;
    NewbieAttendanceReleaseDate: string;
    NewbieAttendanceStartableEndDay: int;
    NewbieAttendanceEndDay: int;
}
table DefaultCharacterExcel {
    CharacterId: long;
    FavoriteCharacter: bool;
    Level: int;
    Exp: int;
    FavorExp: int;
    FavorRank: int;
    StarGrade: int;
    ExSkillLevel: int;
    PassiveSkillLevel: int;
    ExtraPassiveSkillLevel: int;
    CommonSkillLevel: int;
    LeaderSkillLevel: int;
}
table DefaultEchelonExcel {
    EchlonId: int;
    LeaderId: long;
    MainId: [long];
    SupportId: [long];
    TssId: long;
}
table EventContentBoxGachaElementExcel {
    EventContentId: long;
    Id: long;
    Round: long;
    GroupId: long;
}
table FieldCurtainCallFreeModeExcel {
    UniqueId: long;
    OpenDate: long;
    SetFieldDateID: long;
    SetFieldQuestOpenDate: long;
}
table FieldEvidenceExcel {
    UniqueId: long;
    SeasonId: long;
    NameLocalizeKey: string;
    DescriptionLocalizeKey: string;
    DetailLocalizeKey: string;
    ImagePath: string;
}
table FieldKeywordExcel {
    UniqueId: long;
    SeasonId: long;
    NameLocalizeKey: string;
    DescriptionLocalizeKey: string;
    ImagePath: string;
}
table FieldMasteryLevelExcel {
    Level: int;
    Id: [long];
    Exp: [long];
    TotalExp: [long];
    RewardId: [long];
}
table FieldMasteryManageExcel {
    FieldSeason: long;
    LocalizeEtc: uint;
    ImagePath: string;
    LevelId: long;
}
table FieldQuestExcel {
    FieldSeasonId: long;
    UniqueId: long;
    IsDaily: bool;
    FieldDateId: long;
    Opendate: long;
    AssetPath: string;
    RewardId: long;
    Prob: int;
    QuestNamKey: uint;
    QuestDescKey: uint;
}
table FieldSceneExcel {
    UniqueId: long;
    DateId: long;
    GroupId: long;
    ArtLevelPath: string;
    DesignLevelPath: string;
    BGMId: long;
    ConditionalBGMQuestId: [long];
    BeginConditionalBGMScenarioGroupId: [long];
    BeginConditionalBGMInteractionId: [long];
    EndConditionalBGMScenarioGroupId: [long];
    EndConditionalBGMInteractionId: [long];
    ConditionalBGMId: [long];
}
table FieldTutorialExcel {
    SeasonId: long;
    TutorialType: [int];
    ConditionType: [int];
    ConditionId: [long];
}
table GachaSelectPickupGroupExcel {
    Id: long;
    NameKr: string;
    GachaGroupID: long;
    CharacterId: long;
}
table LimitedStageSeasonExcel {
    Id: long;
    StartDate: string;
    EndDate: string;
    TypeACount: long;
    TypeBCount: long;
    TypeCCount: long;
}
table LocalizeCCGExcel {
    Key: uint;
    Kr: string;
    Jp: string;
}
table LocalizeFieldExcel {
    Key: uint;
    Kr: string;
    Jp: string;
}
table MinigameCardExcel {
    None: [int];
}
table ScenarioScriptField1Excel {
    GroupId: long;
    SelectionGroup: long;
    BGMId: long;
    Sound: string;
    Transition: uint;
    BGName: uint;
    BGEffect: uint;
    PopupFileName: string;
    ScriptKr: string;
    TextJp: string;
    VoiceJp: string;
}
table TacticSimulatorSettingExcel {
    GroundId: long;
    FixedEchelonId: long;
}
table TacticTimeAttackSimulatorConfigExcel {
    Order: long;
    Repeat: long;
    PresetGroupId: long;
    AttackStrikerNum: long;
    AttackSpecialNum: long;
    GeasId: long;
}
table AnimationBlendTable {
    DataList: [BlendData];
}
table AnimatorData {
    DefaultStateName: string;
    Name: string;
    DataList: [AniStateData];
}
table AnimatorDataTable {
    DataList: [AnimatorData];
}
table AniStateData {
    StateName: string;
    StatePrefix: string;
    StateNameWithPrefix: string;
    Tag: string;
    SpeedParameterName: string;
    SpeedParamter: float;
    StateSpeed: float;
    ClipName: string;
    Length: float;
    FrameRate: float;
    IsLooping: bool;
    Events: [AniEventData];
}
table BlendData {
    Type: int;
    InfoList: [BlendInfo];
}
table BossPhaseExcelTable {
    DataList: [BossPhaseExcel];
}
table CharacterDialogEmojiExcelTable {
    DataList: [CharacterDialogEmojiExcel];
}
table CharacterDialogFieldExcel {
    GroupId: long;
    Phase: int;
    TargetIndex: int;
    DialogType: FieldDialogType;
    Duration: long;
    MotionName: string;
    IsInteractionDialog: bool;
    HideUI: bool;
    LocalizeKR: string;
    LocalizeJP: string;
}
table CharacterDialogFieldExcelTable {
    DataList: [CharacterDialogFieldExcel];
}
table ClearDeckRuleExcel {
    ContentType: ContentType;
    SizeLimit: long;
}
table ClearDeckRuleExcelTable {
    DataList: [ClearDeckRuleExcel];
}
table ConquestStepExcel {
    EventContentId: long;
    MapDifficulty: StageDifficulty;
    Step: int;
    StepGoalLocalize: string;
    StepEnterScenarioGroupId: long;
    StepEnterItemType: ParcelType;
    StepEnterItemUniqueId: long;
    StepEnterItemAmount: long;
    UnexpectedEventUnitId: [long];
    UnexpectedEventPrefab: string;
    TreasureBoxObjectId: long;
    TreasureBoxCountPerStepOpen: int;
}
table ConquestStepExcelTable {
    DataList: [ConquestStepExcel];
}
table ConstArenaExcel {
    AttackCoolTime: long;
    BattleDuration: long;
    DefenseCoolTime: long;
    TSSStartCoolTime: long;
    EndAlarm: long;
    TimeRewardMaxAmount: long;
    EnterCostType: ParcelType;
    EnterCostId: long;
    TicketCost: long;
    DailyRewardResetTime: string;
    OpenScenarioId: string;
    CharacterSlotHideRank: [long];
    MapSlotHideRank: long;
    RelativeOpponentRankStart: [long];
    RelativeOpponentRankEnd: [long];
    ModifiedStatType: [int];
    StatMulFactor: [long];
    StatSumFactor: [long];
    NPCName: [string];
    NPCMainCharacterCount: long;
    NPCSupportCharacterCount: long;
    NPCCharacterSkillLevel: long;
    TimeSpanInDaysForBattleHistory: long;
    HiddenCharacterImagePath: string;
    DefenseVictoryRewardMaxCount: long;
    TopRankerCountLimit: long;
    AutoRefreshIntervalMilliSeconds: long;
    EchelonSettingIntervalMilliSeconds: long;
    SkipAllowedTimeMilliSeconds: long;
    ShowSeasonChangeInfoStartTime: string;
    ShowSeasonChangeInfoEndTime: string;
    ShowSeasonId: long;
    ArenaHistoryQueryLimitDays: int;
}
table ConstArenaExcelTable {
    DataList: [ConstArenaExcel];
}
table ConstAudioExcelTable {
    DataList: [ConstAudioExcel];
}
table ConstCombatExcelTable {
    DataList: [ConstCombatExcel];
}
table ConstCommonExcel {
    CampaignMainStageMaxRank: int;
    CampaignMainStageBestRecord: int;
    HardAdventurePlayCountRecoverDailyNumber: int;
    HardStageCount: int;
    TacticRankClearTime: int;
    BaseTimeScale: long;
    GachaPercentage: int;
    AcademyFavorZoneId: long;
    CafePresetSlotCount: int;
    CafeMonologueIntervalMillisec: long;
    CafeMonologueDefaultDuration: long;
    CafeBubbleIdleDurationMilliSec: long;
    FindGiftTimeLimit: int;
    CafeAutoChargePeriodInMsc: int;
    CafeProductionDecimalPosition: int;
    CafeSetGroupApplyCount: int;
    WeekDungeonFindGiftRewardLimitCount: int;
    StageFailedCurrencyRefundRate: int;
    EnterDeposit: int;
    AccountMaxLevel: int;
    MainSquadExpBonus: int;
    SupportSquadExpBonus: int;
    AccountExpRatio: int;
    MissionToastLifeTime: int;
    ExpItemInsertLimit: int;
    ExpItemInsertAccelTime: int;
    CharacterLvUpCoefficient: int;
    EquipmentLvUpCoefficient: int;
    ExpEquipInsertLimit: int;
    EquipLvUpCoefficient: int;
    NicknameLength: int;
    CraftDuration: [int];
    CraftLimitTime: int;
    ShiftingCraftDuration: [int];
    ShiftingCraftTicketConsumeAmount: int;
    ShiftingCraftSlotMaxCapacity: int;
    CraftTicketItemUniqueId: int;
    CraftTicketConsumeAmount: int;
    AcademyEnterCostType: ParcelType;
    AcademyEnterCostId: long;
    AcademyTicketCost: int;
    MassangerMessageExpireDay: int;
    CraftLeafNodeGenerateLv1Count: int;
    CraftLeafNodeGenerateLv2Count: int;
    TutorialGachaShopId: int;
    BeforehandGachaShopId: int;
    TutorialGachaGoodsId: int;
    EquipmentSlotOpenLevel: [int];
    ScenarioAutoDelayMillisec: float;
    JoinOrCreateClanCoolTimeFromHour: long;
    ClanMaxMember: long;
    ClanSearchResultCount: long;
    ClanMaxApplicant: long;
    ClanRejoinCoolTimeFromSecond: long;
    ClanWordBalloonMaxCharacter: int;
    CallNameRenameCoolTimeFromHour: long;
    CallNameMinimumLength: long;
    CallNameMaximumLength: long;
    LobbyToScreenModeWaitTime: long;
    ScreenshotToLobbyButtonHideDelay: long;
    PrologueScenarioID01: long;
    PrologueScenarioID02: long;
    TutorialHardStage11: long;
    TutorialSpeedButtonStage: long;
    TutorialCharacterDefaultCount: long;
    TutorialShopCategoryType: ShopCategoryType;
    AdventureStrategyPlayTimeLimitInSeconds: long;
    WeekDungoenTacticPlayTimeLimitInSeconds: long;
    RaidTacticPlayTimeLimitInSeconds: long;
    RaidOpponentListAmount: long;
    CraftBaseGoldRequired: [long];
    PostExpiredDayAttendance: int;
    PostExpiredDayInventoryOverflow: int;
    PostExpiredDayGameManager: int;
    UILabelCharacterWrap: string;
    RequestTimeOut: float;
    MailStorageSoftCap: int;
    MailStorageHardCap: int;
    ClearDeckStorageSize: int;
    ClearDeckNoStarViewCount: int;
    ClearDeck1StarViewCount: int;
    ClearDeck2StarViewCount: int;
    ClearDeck3StarViewCount: int;
    ExSkillLevelMax: int;
    PublicSkillLevelMax: int;
    PassiveSkillLevelMax: int;
    ExtraPassiveSkillLevelMax: int;
    AccountCommentMaxLength: int;
    CafeSummonCoolTimeFromHour: int;
    LimitedStageDailyClearCount: long;
    LimitedStageEntryTimeLimit: long;
    LimitedStageEntryTimeBuffer: long;
    LimitedStagePointAmount: long;
    LimitedStagePointPerApMin: long;
    LimitedStagePointPerApMax: long;
    AccountLinkReward: int;
    MonthlyProductCheckDays: int;
    WeaponLvUpCoefficient: int;
    ShowRaidMyListCount: int;
    RaidEnterCostType: ParcelType;
    RaidEnterCostId: long;
    RaidTicketCost: long;
    TimeAttackDungeonScenarioId: string;
    TimeAttackDungoenPlayCountPerTicket: int;
    TimeAttackDungeonEnterCostType: ParcelType;
    TimeAttackDungeonEnterCostId: long;
    TimeAttackDungeonEnterCost: long;
    ClanLeaderTransferLastLoginLimit: long;
    MonthlyProductRepurchasePopupLimit: int;
    CommonFavorItemTags: [int];
    MaxApMasterCoinPerWeek: long;
    CraftOpenExpTier1: long;
    CraftOpenExpTier2: long;
    CraftOpenExpTier3: long;
    CharacterEquipmentGearSlot: long;
    BirthDayDDay: int;
    RecommendedFriendsLvDifferenceLimit: int;
    DDosDetectCount: int;
    DDosCheckIntervalInSeconds: int;
    MaxFriendsCount: int;
    MaxFriendsRequest: int;
    FriendsSearchRequestCount: int;
    FriendsMaxApplicant: int;
    IdCardDefaultCharacterId: long;
    IdCardDefaultBgId: long;
    WorldRaidGemEnterCost: long;
    WorldRaidGemEnterAmout: long;
    FriendIdCardCommentMaxLength: long;
    FormationPresetNumberOfEchelonTab: int;
    FormationPresetNumberOfEchelon: int;
    FormationPresetRecentNumberOfEchelon: int;
    FormationPresetEchelonTabTextLength: int;
    FormationPresetEchelonSlotTextLength: int;
    CharProfileRowIntervalKr: int;
    CharProfileRowIntervalJp: int;
    CharProfilePopupRowIntervalKr: int;
    CharProfilePopupRowIntervalJp: int;
    BeforehandGachaCount: int;
    BeforehandGachaGroupId: int;
    RenewalDisplayOrderDay: int;
    EmblemDefaultId: long;
    BirthdayMailStartDate: string;
    BirthdayMailRemainDate: int;
    BirthdayMailParcelType: ParcelType;
    BirthdayMailParcelId: long;
    BirthdayMailParcelAmount: int;
    ClearDeckAverageDeckCount: int;
    ClearDeckWorldRaidSaveConditionCoefficient: int;
    ClearDeckShowCount: int;
    CharacterMaxLevel: int;
    PotentialBonusStatMaxLevelMaxHP: int;
    PotentialBonusStatMaxLevelAttackPower: int;
    PotentialBonusStatMaxLevelHealPower: int;
    PotentialOpenConditionCharacterLevel: int;
    AssistStrangerMinLevel: int;
    AssistStrangerMaxLevel: int;
    MaxBlockedUserCount: int;
    CafeRandomVisitMinComfortBonus: long;
    CafeRandomVisitMinLastLogin: int;
    CafeTravelSyncIntervalByMillisec: int;
    RankBracketPercentage1: int;
    RankBracketPercentage2: int;
    RankBracketPercentage3: int;
    RankBracketPercentage4: int;
    RankBracketPercentage5: int;
    RankBracketPercentage6: int;
    RankBracketPercentage7: int;
    ExpiryBattlePassItemReceiveDay: int;
    BattlePassFlavorTextIdleDurationMilliSec: long;
    BattlePassEndImminentDay: int;
    BattlePassExpIconPath: string;
    CafeCameraDragThreshold: float;
    CafeSummonTicketBuyLimitForValidate: int;
    AutoCraftPresetCountLimit: int;
    AutoCraftNodeSelectCount: int;
}
table ConstCommonExcelTable {
    DataList: [ConstCommonExcel];
}
table ConstConquestExcelTable {
    DataList: [ConstConquestExcel];
}
table ConstEventCommonExcel {
    EventContentHardStageCount: int;
    EventStrategyPlayTimeLimitInSeconds: long;
    SubEventChangeLimitSeconds: long;
    SubEventInstantClear: bool;
    CardShopProbWeightCount: long;
    CardShopProbWeightRarity: Rarity;
    MeetupScenarioReplayResource: string;
    MeetupScenarioReplayTitleLocalize: string;
    SpecialOperactionCollectionGroupId: long;
    TreasureNormalVariationAmount: int;
    TreasureLoopVariationAmount: int;
    TreasureLimitVariationLoopCount: int;
    TreasureLimitVariationClearLoopCount: int;
    EventStoryReplayHideEventContentId: int;
}
table ConstEventCommonExcelTable {
    DataList: [ConstEventCommonExcel];
}
table ConstFieldExcelTable {
    DataList: [ConstFieldExcel];
}
table ConstMinigameCCGExcelTable {
    DataList: [ConstMinigameCCGExcel];
}
table ConstMinigameRoadPuzzleExcelTable {
    DataList: [ConstMinigameRoadPuzzleExcel];
}
table ConstMiniGameShootingExcelTable {
    DataList: [ConstMiniGameShootingExcel];
}
table ConstMinigameTBGExcelTable {
    DataList: [ConstMinigameTBGExcel];
}
table ConstNewbieContentExcelTable {
    DataList: [ConstNewbieContentExcel];
}
table ConstStrategyExcel {
    HexaMapBoundaryOffset: float;
    HexaMapStartCameraOffset: float;
    CameraZoomMax: float;
    CameraZoomMin: float;
    CameraZoomDefault: float;
    HealCostType: CurrencyTypes;
    HealCostAmount: [long];
    CanHealHpRate: int;
    PlayTimeLimitInSeconds: long;
    AdventureEchelonCount: int;
    RaidEchelonCount: int;
    DefaultEchelonCount: int;
    EventContentEchelonCount: int;
    TimeAttackDungeonEchelonCount: int;
    WorldRaidEchelonCount: int;
    TacticSkipClearTimeSeconds: int;
    TacticSkipFramePerSecond: int;
    ConquestEchelonCount: int;
    StoryEchelonCount: int;
    MultiSweepPresetCount: int;
    MultiSweepPresetNameMaxLength: int;
    MultiSweepPresetSelectStageMaxCount: int;
    MultiSweepPresetMaxSweepCount: int;
    MultiSweepPresetSelectParcelMaxCount: int;
}
table ConstStrategyExcelTable {
    DataList: [ConstStrategyExcel];
}
table CouponStuffExcel {
    StuffId: long;
    ParcelType: ParcelType;
    ParcelId: long;
    LimitAmount: int;
    CouponStuffNameLocalizeKey: string;
}
table CouponStuffExcelTable {
    DataList: [CouponStuffExcel];
}
table DefaultCharacterExcelTable {
    DataList: [DefaultCharacterExcel];
}
table DefaultEchelonExcelTable {
    DataList: [DefaultEchelonExcel];
}
table DefaultFurnitureExcel {
    Id: long;
    Location: FurnitureLocation;
    PositionX: float;
    PositionY: float;
    Rotation: float;
}
table DefaultFurnitureExcelTable {
    DataList: [DefaultFurnitureExcel];
}
table DefaultMailExcel {
    Id: long;
    LocalizeCodeId: uint;
    MailType: MailType;
    MailSendPeriodFrom: string;
    MailSendPeriodTo: string;
    RewardParcelType: [int];
    RewardParcelId: [long];
    RewardParcelAmount: [long];
}
table DefaultMailExcelTable {
    DataList: [DefaultMailExcel];
}
table DefaultParcelExcel {
    ParcelType: ParcelType;
    ParcelId: long;
    ParcelAmount: long;
}
table DefaultParcelExcelTable {
    DataList: [DefaultParcelExcel];
}
table EventContentBoxGachaElementExcelTable {
    DataList: [EventContentBoxGachaElementExcel];
}
table FieldContentStageExcel {
    Id: long;
    SeasonId: long;
    AreaId: long;
    GroupId: long;
    StageDifficulty: StageDifficulty;
    PrevStageId: long;
    Name: string;
    BattleDuration: long;
    StageEnterCostType: ParcelType;
    StageEnterCostId: long;
    StageEnterCostAmount: int;
    StageTopography: StageTopography;
    RecommandLevel: int;
    GroundID: long;
    BGMId: long;
    InstantClear: bool;
    FixedEchelonId: long;
    SkipFormationSettings: bool;
    DailyLastPlay: bool;
    StarGoal: [int];
    StarGoalAmount: [int];
}
table FieldContentStageExcelTable {
    DataList: [FieldContentStageExcel];
}
table FieldContentStageRewardExcel {
    GroupId: long;
    RewardTag: RewardTag;
    RewardProb: int;
    RewardParcelType: ParcelType;
    RewardId: long;
    RewardAmount: int;
    IsDisplayed: bool;
}
table FieldContentStageRewardExcelTable {
    DataList: [FieldContentStageRewardExcel];
}
table FieldCurtainCallFreeModeExcelTable {
    DataList: [FieldCurtainCallFreeModeExcel];
}
table FieldDateExcel {
    SeasonId: long;
    UniqueId: long;
    OpenDate: long;
    DateLocalizeKey: string;
    EntrySceneId: long;
    StartConditionType: FieldConditionType;
    StartConditionId: long;
    EndConditionType: FieldConditionType;
    EndConditionId: long;
    EndReadyConditionType: FieldConditionType;
    EndReadyConditionId: long;
    OpenConditionStage: long;
    CharacterIconPath: string;
    DateResultBGPath: string;
    DateResultSpinePath: string;
    DateResultSpineOffsetX: float;
}
table FieldDateExcelTable {
    DataList: [FieldDateExcel];
}
table FieldEvidenceExcelTable {
    DataList: [FieldEvidenceExcel];
}
table FieldInteractionExcel {
    FieldSeasonId: long;
    UniqueId: long;
    FieldDateId: long;
    ShowEmoji: bool;
    KeywordLocalize: string;
    InteractionType: [int];
    InteractionId: [long];
    ConditionClass: FieldConditionClass;
    ConditionClassParameters: [long];
    OnceOnly: bool;
    ConditionIndex: [long];
    ConditionType: [int];
    ConditionId: [long];
    NegateCondition: [bool];
}
table FieldInteractionExcelTable {
    DataList: [FieldInteractionExcel];
}
table FieldKeywordExcelTable {
    DataList: [FieldKeywordExcel];
}
table FieldMasteryExcel {
    UniqueId: long;
    SeasonId: long;
    Order: int;
    ExpAmount: long;
    TokenType: ParcelType;
    TokenId: long;
    TokenRequirement: long;
    AccomplishmentConditionType: FieldConditionType;
    AccomplishmentConditionId: long;
}
table FieldMasteryExcelTable {
    DataList: [FieldMasteryExcel];
}
table FieldMasteryLevelExcelTable {
    DataList: [FieldMasteryLevelExcel];
}
table FieldMasteryManageExcelTable {
    DataList: [FieldMasteryManageExcel];
}
table FieldQuestExcelTable {
    DataList: [FieldQuestExcel];
}
table FieldRewardExcel {
    GroupId: long;
    RewardProb: int;
    RewardParcelType: ParcelType;
    RewardId: long;
    RewardAmount: int;
}
table FieldRewardExcelTable {
    DataList: [FieldRewardExcel];
}
table FieldSceneExcelTable {
    DataList: [FieldSceneExcel];
}
table FieldSeasonExcel {
    UniqueId: long;
    EventContentId: long;
    EntryDateId: long;
    InstantEntryDateId: long;
    StartDate: string;
    EndDate: string;
    LobbyBGMChangeStageId: long;
    FieldPrefabControlID: long;
    FieldGetKeywordCallDialogEnum: FieldDialogType;
    MasteryImagePath: string;
    FieldLobbyTitleImagePath: string;
    KeywordLogoImagePath: string;
}
table FieldSeasonExcelTable {
    DataList: [FieldSeasonExcel];
}
table FieldStoryStageExcel {
    Id: long;
    SeasonId: long;
    Name: string;
    BattleDuration: long;
    StageTopography: StageTopography;
    RecommandLevel: int;
    GroundID: long;
    BGMId: long;
    FixedEchelonId: long;
    SkipFormationSettings: bool;
}
table FieldStoryStageExcelTable {
    DataList: [FieldStoryStageExcel];
}
table FieldTutorialExcelTable {
    DataList: [FieldTutorialExcel];
}
table FieldWorldMapZoneExcel {
    Id: long;
    GroupId: int;
    Date: int;
    OpenConditionType: FieldConditionType;
    OpenConditionId: long;
    CloseConditionType: FieldConditionType;
    CloseConditionId: long;
    ResultFieldScene: long;
    FieldStageInteractionId: long;
    WorldMapButtonType: FieldWorldMapButtonType;
    LocalizeCode: uint;
    NewTagDisplay: bool;
}
table FieldWorldMapZoneExcelTable {
    DataList: [FieldWorldMapZoneExcel];
}
table GachaSelectPickupGroupExcelTable {
    DataList: [GachaSelectPickupGroupExcel];
}
table LimitedStageExcel {
    Id: long;
    Name: string;
    SeasonId: long;
    StageDifficulty: StageDifficulty;
    StageNumber: string;
    StageDisplay: int;
    PrevStageId: long;
    OpenDate: long;
    OpenEventPoint: long;
    BattleDuration: long;
    StageEnterCostType: ParcelType;
    StageEnterCostId: long;
    StageEnterCostAmount: int;
    StageEnterEchelonCount: int;
    StarConditionTacticRankSCount: long;
    StarConditionTurnCount: long;
    EnterScenarioGroupId: [long];
    ClearScenarioGroupId: [long];
    StrategyMap: string;
    StrategyMapBG: string;
    StageRewardId: long;
    MaxTurn: int;
    StageTopography: StageTopography;
    RecommandLevel: int;
    BgmId: string;
    StrategyEnvironment: StrategyEnvironment;
    GroundID: long;
    ContentType: ContentType;
    BGMId: long;
    InstantClear: bool;
    BuffContentId: long;
    ChallengeDisplay: bool;
}
table LimitedStageExcelTable {
    DataList: [LimitedStageExcel];
}
table LimitedStageRewardExcel {
    GroupId: long;
    RewardTag: RewardTag;
    RewardProb: int;
    RewardParcelType: ParcelType;
    RewardId: long;
    RewardAmount: int;
    IsDisplayed: bool;
}
table LimitedStageRewardExcelTable {
    DataList: [LimitedStageRewardExcel];
}
table LimitedStageSeasonExcelTable {
    DataList: [LimitedStageSeasonExcel];
}
table LocalizeCCGExcelTable {
    DataList: [LocalizeCCGExcel];
}
table LocalizeFieldExcelTable {
    DataList: [LocalizeFieldExcel];
}
table MinigameCardExcelTable {
    DataList: [MinigameCardExcel];
}
table ProtocolSettingExcel {
    Protocol: string;
    OpenConditionContent: OpenConditionContent;
    Currency: bool;
    Inventory: bool;
    Mail: bool;
}
table ProtocolSettingExcelTable {
    DataList: [ProtocolSettingExcel];
}
table ScenarioReplayExcel {
    ModeId: long;
    VolumeId: long;
    ReplayType: ScenarioModeReplayTypes;
    ChapterId: long;
    EpisodeId: long;
    FrontScenarioGroupId: [long];
    GroundId: long;
    BattleDuration: long;
    BackScenarioGroupId: [long];
}
table ScenarioReplayExcelTable {
    DataList: [ScenarioReplayExcel];
}
table ScenarioScriptField1ExcelTable {
    DataList: [ScenarioScriptField1Excel];
}
table SystemMailExcel {
    MailType: MailType;
    ExpiredDay: long;
    Sender: string;
    Comment: string;
}
table SystemMailExcelTable {
    DataList: [SystemMailExcel];
}
table TacticArenaSimulatorSettingExcel {
    Order: long;
    Repeat: long;
    AttackerFrom: ArenaSimulatorServer;
    AttackerUserArenaGroup: long;
    AttackerUserArenaRank: long;
    AttackerPresetGroupId: long;
    AttackerStrikerNum: long;
    AttackerSpecialNum: long;
    DefenderFrom: ArenaSimulatorServer;
    DefenderUserArenaGroup: long;
    DefenderUserArenaRank: long;
    DefenderPresetGroupId: long;
    DefenderStrikerNum: long;
    DefenderSpecialNum: long;
    GroundId: long;
}
table TacticArenaSimulatorSettingExcelTable {
    DataList: [TacticArenaSimulatorSettingExcel];
}
table TacticDamageSimulatorSettingExcel {
    Order: int;
    Repeat: int;
    TestPreset: long;
    TestBattleTime: long;
    StrikerSquard: long;
    SpecialSquard: long;
    ReplaceCharacterCostRegen: bool;
    ReplaceCostRegenValue: int;
    UseAutoSkill: bool;
    OverrideStreetAdaptation: TerrainAdaptationStat;
    OverrideOutdoorAdaptation: TerrainAdaptationStat;
    OverrideIndoorAdaptation: TerrainAdaptationStat;
    ApplyOverrideAdaptation: bool;
    OverrideFavorLevel: int;
    ApplyOverrideFavorLevel: bool;
    GroundId: long;
    FixedCharacter: [long];
}
table TacticDamageSimulatorSettingExcelTable {
    DataList: [TacticDamageSimulatorSettingExcel];
}
table TacticSimulatorSettingExcelTable {
    DataList: [TacticSimulatorSettingExcel];
}
table TacticTimeAttackSimulatorConfigExcelTable {
    DataList: [TacticTimeAttackSimulatorConfigExcel];
}
table TagExcel {
    Furniture: Tag;
    None: Club;
}
table TagExcelTable {
    DataList: [TagExcel];
}
